/*
  LICENSE: MIT
  Created by: Lightnet
*/

export const API = {
    GET:"GET"
  , POST:"POST"
  , DELETE:"DELETE"
  , PUT:"PUT"
  , PATCH:"PATCH"
  , ERROR:"ERROR"
  , FAIL:"FAIL"
  , PASS:"PASS"
  , NONE:"NONE"
  , WARN:"WARN"
  , LOG:"LOG"
  , INFO:"INFO"
  , TYPES:{
      MESSAGE:"MESSAGE"
    , MESSAGES:"MESSAGES"
    , POSTS:"POSTS"
    , CREATE:"CREATE"
    , UPDATE:"UPDATE"
    , EDIT:"EDIT"
    , EXIST:"EXIST"
    , SEND:"SEND"
    , SENT:"SENT"
  },
  AUTHS:{
      EXISTS:"EXISTS"
    , LOGIN:"LOGIN"
    , SIGNIN:"SIGNIN"
    , LOGOUT:"LOGOUT"
    , SIGNOUT:"SIGNOUT"
    , SIGNUP:"SIGNUP"
    , REGISTER:"REGISTER"
    , ACCESS:"ACCESS"
    , PASSWORDFAIL:"PASSWORDFAIL"
    , PASSPHRASEFAIL:"PASSPHRASEFAIL"
    , CHANGE:"CHANGE"
  }
}