/*
  LICENSE: MIT
  Created by: Lightnet
*/

var API = {
    CREATE:"CREATE"
  , GET:"GET"
  , POST:"POST"
  , PUT:"PUT"
  , UPDATE:"UPDATE"
  , DELETE:"DELETE"
  , LIST:"LIST"
  , PROJECT:"PROJECT"
  , SCENES:"SCENES"
  , ENTITYTYPES:{
      SCENE:"SCENE"
    , CAMERA:"CAMERA"
    
    , AMBIENTLIGHT:"AMBIENTLIGHT"
    , POINTLIGHT:"POINTLIGHT"
    , DIRECTONALLIGHT: "DIRECTONALLIGHT"
    , HEMISPHERELIGHT: "HEMISPHERELIGHT"
    , RECTAREALIGHT: "RECTAREALIGHT"
    , SPOTLIGHT: "SPOTLIGHT"

    , BOX:"BOX"
    , CAPSULE:"CAPSULE"
    , CIRCLE:"CIRCLE"
    , CONE:"CONE"
    , CYLINDER:"CYLINDER"
    , DODECAHEDRON:"DODECAHEDRON"
    , ICOSAHEDRON:"ICOSAHEDRON"
    , OCTAHEDRON:"OCTAHEDRON"
    , PLANE:"PLANE"
    , RING:"RING"
    , SPHERE:"SPHERE"
    , TETRAHERDON:"TETRAHERDON"
    , TORUS:"TORUS"
    , TORUSKNOT:"TORUSKNOT"
    
    , MODELFBX:"MODELFBX"
    , MODELGLTF:"MODELGLTF"
  }
}

export {
  API
}