/*
  LICENSE: MIT
  Created by: Lightnet
*/

var API = {
  ENTITYTYPES:{
      SCENE:"SCENE"
    , CAMERA:"CAMERA"
    , AMBIENTLIGHT:"AMBIENTLIGHT"
    , POINTLIGHT:"POINTLIGHT"
    , DIRECTONALLIGHT: "DIRECTONALLIGHT"
    , HEMISPHERELIGHT: "HEMISPHERELIGHT"
    , RECTAREALIGHT: "RECTAREALIGHT"
    , SPOTLIGHT: "SPOTLIGHT"

    , BOX:"BOX"
    , PLANE:"PLANE"
    , SPHERE:"SPHERE"
    , CYLINDER:"CYLINDER"

    , MODELFBX:"MODELFBX"
    , MODELGLTF:"MODELGLTF"
  }
}

export {
  API
}