/*
  LICENSE: MIT
  Created by: Lightnet
*/

// https://github.com/pmndrs/cannon-es/tree/265d47476df6a47e9650bcdc4dd34ede608aa5a6/src/shapes

var API = {
    CREATE:"CREATE"
  , GET:"GET"
  , POST:"POST"
  , PUT:"PUT"
  , UPDATE:"UPDATE"
  , DELETE:"DELETE"
  , LIST:"LIST"
  , PROJECT:"PROJECT"
  , SCENES:"SCENES"
  , SHAPES:{
    NULL:"null",
    BOX:"BOX",
    SPHERE:"SPHERE",
    PLANE:"PLANE",
    CYLINDER:"CYLINDER",
    HEIGHTFIELD:"HEIGHTFIELD",
    TRIMESH:"TRIMESH",
  }
  , ENTITYTYPES:{
      SCENE:"SCENE"
    , CAMERA:"CAMERA"
    
    , AMBIENTLIGHT:"AMBIENTLIGHT"
    , POINTLIGHT:"POINTLIGHT"
    , DIRECTONALLIGHT: "DIRECTONALLIGHT"
    , HEMISPHERELIGHT: "HEMISPHERELIGHT"
    , RECTAREALIGHT: "RECTAREALIGHT"
    , SPOTLIGHT: "SPOTLIGHT"

    , BOX:"BOX"
    , CAPSULE:"CAPSULE"
    , CIRCLE:"CIRCLE"
    , CONE:"CONE"
    , CYLINDER:"CYLINDER"
    , DODECAHEDRON:"DODECAHEDRON"
    , ICOSAHEDRON:"ICOSAHEDRON"
    , OCTAHEDRON:"OCTAHEDRON"
    , PLANE:"PLANE"
    , RING:"RING"
    , SPHERE:"SPHERE"
    , TETRAHERDON:"TETRAHERDON"
    , TORUS:"TORUS"
    , TORUSKNOT:"TORUSKNOT"
    
    , MODELFBX:"MODELFBX"
    , MODELGLTF:"MODELGLTF"
  }
}

export {
  API
}